### ISSUE TITLE
uninitialized constant Hashie::Mash::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by thommay** [reset/chozo#27]
I can't figure out if I'm missing something blindingly obvious, or if this is a bug.

class Test < Chozo::Config::Abstract
irb >>   attribute "foo.bar", type: String, default: "foo"
attribute "foo.bar", type: String, default: "foo"
irb >>   end
end
NameError: uninitialized constant Hashie::Mash::HashWithIndifferentAccess
        from /Users/tmay/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/chozo-0.6.1/lib/chozo/hashie_ext/mash.rb:11:in `coercions'
        from /Users/tmay/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/chozo-0.6.1/lib/chozo/hashie_ext/mash.rb:15:in`coercion'
        from /Users/tmay/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/chozo-0.6.1/lib/chozo/hashie_ext/mash.rb:24:in `[]='

**Comment by thommay** [comment]
Ah, not including active_support was the blindingly obvious thing. However, it seems like Hashie has an IndifferentAccess extension; would it be reasonable to mix that in to lib/chozo/hashie_ext/hash.rb ?

**Comment by reset** [comment]
@thommay pretty sure that this was a mistake and a leftover from a while ago. We can fix that up quick!
